class Data {
  static List<List<String>> alphabet = [
    ['A', 'Apple', '🍎'],
    ['B', 'Ball', '⚽'],
    ['C', 'Cat', '🐱'],
    ['D', 'Dog', '🐶'],
    ['E', 'Elephant', '🐘'],
    ['F', 'Fish', '🐟'],
    ['G', 'Giraffe', '🦒'],
    ['H', 'Horse', '🐴'],
    ['I', 'Ice Cream', '🍦'],
    ['J', 'Jellyfish', '🎐'],
    ['K', 'Kangaroo', '🦘'],
    ['L', 'Lion', '🦁'],
    ['M', 'Monkey', '🐒'],
    ['N', 'Noodle', '🍜'],
    ['O', 'Octopus', '🐙'],
    ['P', 'Penguin', '🐧'],
    ['Q', 'Queen', '👑'],
    ['R', 'Rainbow', '🌈'],
    ['S', 'Sun', '☀️'],
    ['T', 'Tree', '🌳'],
    ['U', 'Umbrella', '☂️'],
    ['V', 'Violin', '🎻'],
    ['W', 'Watermelon', '🍉'],
    ['X', 'Xylophone', '🎼'],
    ['Y', 'Yoga', '🧘'],
    ['Z', 'Zebra', '🦓'],
  ];

  static List<List<String>> nepaliVowels = [
    ['अ', 'अनार', '🍅'],
    ['आ', 'आमा', '🤱'],
    ['इ', 'इश्वर', '🕉️'],
    ['ई', 'ईनार', '🕳️'],
    ['उ', 'उल्लु', '🦉'],
    ['ऊ', 'ऊन', '🧶'],
    ['ए', 'एम्बुलेन्स', '🚑'],
    ['ऐ', 'ऐना', '🪞'],
    ['ओ', 'ओखल', '🧉'],
    ['औ', 'औषधि', '💉'],
    ['अं', 'अंगुर', '🍇'],
    ['अः', 'अः', '']
  ];

  static List<List<dynamic>> birdsData = [
    ['assets/birds/crow.jpg', 'Crow'],
    ['assets/birds/eagle.jpg', 'Eagle'],
    ['assets/birds/flamingo.jpg', 'Flamingo'],
    ['assets/birds/hawk.jpg', 'Hawk'],
    ['assets/birds/hummingbird.jpg', 'Hummingbird'],
    ['assets/birds/owl.jpg', 'Owl'],
    ['assets/birds/parrot.jpg', 'Parrot'],
    ['assets/birds/peacock.jpg', 'Peacock'],
    ['assets/birds/pelican.jpg', 'Pelican'],
    ['assets/birds/penguin.jpg', 'Penguin'],
    ['assets/birds/pigeon.jpg', 'Pigeon'],
    ['assets/birds/robin.jpg', 'Robin'],
    ['assets/birds/sparrow.jpg', 'Sparrow'],
    ['assets/birds/swan.jpg', 'Swan'],
    ['assets/birds/woodpecker.jpg', 'Woodpecker'],
    ['assets/birds/chicken.jpg', 'Chicken'],
    ['assets/birds/duck.jpg', 'Duck'],
    ['assets/birds/emu.jpg', 'Emu'],
    ['assets/birds/himalayan_monal.jpg', 'Himalayan Monal'],
    ['assets/birds/ostrich.jpg', 'Ostrich'],
    ['assets/birds/rufous_necked_hornbill.jpg', 'Rufos Necked Hornbill'],
    ['assets/birds/spiny_babbler.jpg', 'Spiny Babbler'],
    ['assets/birds/vulture.jpg', 'Vulture'],
  ];

  static List<List<dynamic>> animalsData = [
    ['assets/animals/dog.jpg', 'Dog'],
    ['assets/animals/cat.jpg', 'Cat'],
    ['assets/animals/cow.jpg', 'Cow'],
    ['assets/animals/goat.jpg', 'Goat'],
    ['assets/animals/pig.jpg', 'Pig'],
    ['assets/animals/sheep.jpg', 'Sheep'],
    ['assets/animals/elephant.jpg', 'Elephant'],
    ['assets/animals/tiger.jpg', 'Tiger'],
    ['assets/animals/lion.jpg', 'Lion'],
    ['assets/animals/monkey.jpg', 'Monkey'],
    ['assets/animals/panda.jpg', 'Panda'],
    ['assets/animals/horse.jpg', 'Horse'],
    ['assets/animals/fox.jpg', 'Fox'],
    ['assets/animals/wolf.jpg', 'Wolf'],
    ['assets/animals/zebra.jpg', 'Zebra'],
    ['assets/animals/gorilla.jpg', 'Gorilla'],
    ['assets/animals/leo.jpg', 'Leopard'],
    ['assets/animals/rhino.jpg', 'Rhinoceros'],
    ['assets/animals/giraffe.jpg', 'Giraffe'],
    ['assets/animals/kangaroo.jpg', 'Kangaroo'],
    ['assets/animals/koala.jpg', 'Koala'],
    ['assets/animals/bear.jpg', 'Bear'],
    ['assets/animals/hippo.jpg', 'Hippopotamus'],
    ['assets/animals/crocodile.jpg', 'Crocodile'],
    ['assets/animals/snake.jpg', 'Snake'],
    ['assets/animals/rabbit.jpg', 'Rabbit'],
    ['assets/animals/fish.jpg', 'Fish'],
    ['assets/animals/frog.jpg', 'Frog'],
    ['assets/animals/turtle.jpg', 'Turtle'],
    ['assets/animals/lizard.jpg', 'Lizard'],
  ];

  static List<List<dynamic>> fruitsAndVegetablesData = [
    ['assets/fruits/apple.jpg', 'Apple'],
    ['assets/fruits/banana.jpg', 'Banana'],
    ['assets/fruits/grapes.jpg', 'Grapes'],
    ['assets/fruits/strawberry.jpg', 'Strawberry'],
    ['assets/fruits/orange.jpg', 'Orange'],
    ['assets/fruits/watermelon.jpg', 'Watermelon'],
    ['assets/fruits/cherry.jpg', 'Cherry'],
    ['assets/fruits/peach.jpg', 'Peach'],
    ['assets/fruits/kiwi.jpg', 'Kiwi'],
    ['assets/fruits/mango.jpg', 'Mango'],
    ['assets/fruits/tomato.jpg', 'Tomato'],
    ['assets/fruits/broccoli.jpg', 'Broccoli'],
    ['assets/fruits/carrot.jpg', 'Carrot'],
    ['assets/fruits/potato.jpg', 'Potato'],
    ['assets/fruits/cucumber.jpg', 'Cucumber'],
    ['assets/fruits/avocado.jpg', 'Avocado'],
    ['assets/fruits/chili.jpg', 'Red Chili Pepper'],
    ['assets/fruits/bottlegourd.jpg', 'Bottle Gourd'],
    ['assets/fruits/cabbage.jpg', 'Cabbage'],
    ['assets/fruits/cauliflower.jpg', 'Cauliflower'],
    ['assets/fruits/colocasia.jpg', 'Colocasia'],
    ['assets/fruits/coriander.jpg', 'Coriander'],
    ['assets/fruits/corn.jpg', 'Corn'],
    ['assets/fruits/cowpea.jpg', 'Cowpea'],
    ['assets/fruits/eggplant.jpg', 'Eggplant'],
    ['assets/fruits/frenchbean.jpg', 'French Bean'],
    ['assets/fruits/garlic.jpg', 'Garlic'],
    ['assets/fruits/ginger.jpg', 'Ginger'],
    ['assets/fruits/greenonion.jpg', 'Green Onion'],
    ['assets/fruits/kidneybeans.jpg', 'Kidney Beans'],
    ['assets/fruits/ladyfinger.jpg', 'Lady finger'],
    ['assets/fruits/lettuce.jpg', 'Lettuce'],
    ['assets/fruits/lime.jpg', 'Lime'],
    ['assets/fruits/mushroom.jpg', 'Mushroom'],
    ['assets/fruits/coconut.jpg', 'Coconut'],
    ['assets/fruits/peas.jpg', 'Peas'],
    ['assets/fruits/pumpkin.jpg', 'Pumpkin'],
    ['assets/fruits/snakegourd.jpg', 'Snake Gourd'],
    ['assets/fruits/onion.jpg', 'Onion'],
    ['assets/fruits/pineapple.jpg', 'Pineapple'],
  ];

  static List<List<dynamic>> vehiclesData = [
    ['assets/vehicles/car.jpg', 'Car'],
    ['assets/vehicles/taxi.jpg', 'Taxi'],
    ['assets/vehicles/SUV.jpg', 'SUV'],
    ['assets/vehicles/bus.jpg', 'Bus'],
    ['assets/vehicles/trolleybus.jpg', 'Trolleybus'],
    ['assets/vehicles/police.jpg', 'Police Car'],
    ['assets/vehicles/ambulance.jpg', 'Ambulance'],
    ['assets/vehicles/fire.jpg', 'Fire Truck'],
    ['assets/vehicles/minibus.jpg', 'Minibus'],
    ['assets/vehicles/truck.jpg', 'Truck'],
    ['assets/vehicles/articulated.jpg', 'Articulated Lorry'],
    ['assets/vehicles/tractor.jpg', 'Tractor'],
    ['assets/vehicles/scooter.jpg', 'Motor Scooter'],
    ['assets/vehicles/motorcycle.jpg', 'Motorcycle'],
    ['assets/vehicles/bicycle.jpg', 'Bicycle'],
    ['assets/vehicles/kick.jpg', 'Kick Scooter'],
    ['assets/vehicles/locomotive.jpg', 'Locomotive'],
    ['assets/vehicles/train.jpg', 'Train'],
    ['assets/vehicles/metro.jpg', 'Metro'],
    ['assets/vehicles/plane.jpg', 'Airplane'],
    ['assets/vehicles/helicopter.jpg', 'Helicopter'],
    ['assets/vehicles/rocket.jpg', 'Rocket'],
  ];
}
