class Data {

static List<List<String>> alphabet = [
      ['A', 'Apple', '🍎'],
      ['B', 'Ball', '⚽'],
      ['C', 'Cat', '🐱'],
      ['D', 'Dog', '🐶'],
      ['E', 'Elephant', '🐘'],
      ['F', 'Fish', '🐟'],
      ['G', 'Giraffe', '🦒'],
      ['H', 'Horse', '🐴'],
      ['I', 'Ice Cream', '🍦'],
      ['J', 'Jellyfish', '🎐'],
      ['K', 'Kangaroo', '🦘'],
      ['L', 'Lion', '🦁'],
      ['M', 'Monkey', '🐒'],
      ['N', 'Noodle', '🍜'],
      ['O', 'Octopus', '🐙'],
      ['P', 'Penguin', '🐧'],
      ['Q', 'Queen', '👑'],
      ['R', 'Rainbow', '🌈'],
      ['S', 'Sun', '☀️'],
      ['T', 'Tree', '🌳'],
      ['U', 'Umbrella', '☂️'],
      ['V', 'Violin', '🎻'],
      ['W', 'Watermelon', '🍉'],
      ['X', 'Xylophone', '🎼'],
      ['Y', 'Yoga', '🧘'],
      ['Z', 'Zebra', '🦓'],
    ];

  static List<List<String>> nepaliVowels = [
      ['अ', 'अनार', '🍅'],
      ['आ', 'आमा', '🤱'],
      ['इ', 'इश्वर', '🕉️'],
      ['ई', 'ईनार', '🕳️'],
      ['उ', 'उल्लु', '🦉'],
      ['ऊ', 'ऊन', '🧶'],
      ['ए', 'एम्बुलेन्स', '🚑'],
      ['ऐ', 'ऐना', '🪞'],
      ['ओ', 'ओखल', '🧉'],
      ['औ', 'औषधि', '💉'],
      ['अं', 'अंगुर', '🍇'],
      ['अः', 'अः', '']
    ];

  static List<List<dynamic>> birdsData = [
    ['🦅', 'Eagle'],
    ['🦆', 'Duck'],
    ['🦜', 'Parrot'],
    ['🦉', 'Owl'],
    ['🦢', 'Swan'],
    ['🦚', 'Peacock'],
    ['🦩', 'Flamingo'],
    ['🐓', 'Rooster'],
    ['🐔', 'Chicken'],
    ['🦤', 'Dodo'],
    ['🐧', 'Penguin'],
    ['🐤', 'Chick'],
    ['🦆', 'Mallard Duck'],
    ['🕊️', 'Angel']
  ];

  static List<List<dynamic>> animalsData = [
    ['🐘', 'Elephant'],
    ['🐅', 'Tiger'],
    ['🦁', 'Lion'],
    ['🐻', 'Bear'],
    ['🐒', 'Monkey'],
    ['🐼', 'Panda'],
    ['🐎', 'Horse'],
    ['🦊', 'Fox'],
    ['🦋', 'Butterfly'],
    ['🐞', 'Ladybug'],
    ['🐺', 'Wolf'],
    ['🦓', 'Zebra'],
    ['🦍', 'Gorilla'],
    ['🐆', 'Leopard'],
    ['🦏', 'Rhinoceros'],
    ['🐖', 'Pig'],
    ['🐏', 'Sheep'],
    ['🐠', 'Fish'],
    ['🐊', 'Crocodile'],
    ['🐢', 'Turtle'],
    ['🐍', 'Snake'],
    ['🦎', 'Lizard'],
    ['🐙', 'Octopus'],
    ['🦈', 'Shark'],
    ['🐋', 'Whale'],
    ['🐸', 'Frog'],
    ['🐢', 'Tortoise'],
    ['🐆', 'Cheetah'],
    ['🦇', 'Bat'],
    ['🐿️', 'Squirrel'],
    ['🐃', 'Buffalo'],
    ['🦌', 'Deer'],
    ['🦛', 'Hippopotamus'],
    ['🐴', 'Horse'],
    ['🐁', 'Mouse'],
    ['🐉', 'Dragon'],
    ['🦕', 'Dinosaur'],
    ['🦔', 'Hedgehog'],
    ['🐢', 'Terrapin'],
    ['🦀', 'Crab'],
  ];

  static  List<List<dynamic>>  fruitsAndVegetablesData = [
    ['🍎', 'Apple'],
    ['🍌', 'Banana'],
    ['🍇', 'Grapes'],
    ['🍓', 'Strawberry'],
    ['🍊', 'Orange'],
    ['🍉', 'Watermelon'],
    ['🍍', 'Pineapple'],
    ['🍒', 'Cherry'],
    ['🍑', 'Peach'],
    ['🥥', 'Coconut'],
    ['🥝', 'Kiwi'],
    ['🥭', 'Mango'],
    ['🍅', 'Tomato'],
    ['🥦', 'Broccoli'],
    ['🥕', 'Carrot'],
    ['🥔', 'Potato'],
    ['🥒', 'Cucumber'],
    ['🌽', 'Corn'],
    ['🥬', 'Leafy Greens'],
    ['🥑', 'Avocado'],
    ['🌶️', 'Red Chili Pepper'],
  ];

  static List<List<dynamic>> vehiclesData = [
    ['🚗', 'Car'],
    ['🚕', 'Taxi'],
    ['🚙', 'SUV'],
    ['🚌', 'Bus'],
    ['🚎', 'Trolleybus'],
    ['🚓', 'Police Car'],
    ['🚑', 'Ambulance'],
    ['🚒', 'Fire Truck'],
    ['🚐', 'Minibus'],
    ['🚚', 'Truck'],
    ['🚛', 'Articulated Lorry'],
    ['🚜', 'Tractor'],
    ['🛵', 'Motor Scooter'],
    ['🏍️', 'Motorcycle'],
    ['🚲', 'Bicycle'],
    ['🛴', 'Kick Scooter'],
    ['🚂', 'Locomotive'],
    ['🚆', 'Train'],
    ['🚇', 'Metro'],
    ['✈️', 'Airplane'],
    ['🚁', 'Helicopter'],
    ['🚀', 'Rocket'],
  ];
}
